### PR TITLE
Fix rubocop issues in models

### LINKED ISSUE #354: Fix rubocop issues in models

### PR DESCRIPTION
**Pull request by arun1595**
Still, we get 3 issues from rubocop's analysis. Not sure how to resolve them.

Fixes #354

### CODE REVIEW

File: app/models/lesson.rb [hunk 1]
```diff
@@ -56,14 +56,14 @@ def find_lesson
...
+  def slug_candidates
     [
       :title,
       [:title, course_title]
     ]
   end
 
   def course_title
-    course.title if course
+    course&.title
```
Comment (KevinMulhern) [inline app/models/lesson.rb]: I haven't seen anything like this before 😄  what does the & do?

**Comment by KevinMulhern** [comment]
LGTM 👍

File: app/models/lesson.rb (hunk 1 above)
Comment (KevinMulhern) [inline app/models/lesson.rb]: Nice!

**Comment by KevinMulhern** [comment]
👍 LGTM
