### PR TITLE
Fix rubocop issues

### LINKED ISSUE #351: Fix rubocop issues in controllers

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #351

### CODE REVIEW

File: app/controllers/lesson_completions_controller.rb [hunk 1]
```diff
@@ -15,7 +15,9 @@ def destroy
   private
 
   def lesson_completion
```
Comment (KevinMulhern) [inline app/controllers/lesson_completions_controller.rb]: I think this one looks a little disjointed, maybe this would be cleaner looking?
```
LessonCompletion.where(
  student_id: current_user.id,
  lesson_id: @lesson.id
).first
```

**Comment by KevinMulhern** [comment]
👍 LGTM
Great work Arun 😄
