### PR TITLE
Fix: Add gold colour to 'view all submissions link' (#3391)

### LINKED ISSUE #3391: Bug: 'View full list of solutions' links are not colored
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

view full list

`View full list of solutions` links from the project pages are not colored. I have seen some project pages of the Javascript course of Full stack Javascript path and all of them have the same problem. Because of this, it is not clear if the link is a link or just text.

**2. How To Reproduce:**

1. Log in
2. Visit [Project:recursion](https://www.theodinproject.com/lessons/javascript-recursion) page.
3. Scroll until `Next lesson` button.
4. Above the button there is the `View full list of collections` link.

**3. Expected Behavior:**

The link should have a gold like color that all other links in the curriculum have.

**4. Desktop/Device:**

-   Device:  laptop, android mobile
-   OS:  android, linux
-   Browser:  firefox, android chrome
-   Version: 
**5. Additional Information:**

### PR DESCRIPTION
**Pull request by ChargrilledChook**
Because:
  * Links should be coloured gold so it's obvious they are links
   * Closes #3391 
 
Post Fix:
image

### CODE REVIEW

File: app/javascript/components/project-submissions/components/submissions-list.jsx [hunk 1]
```diff
@@ -67,7 +67,13 @@ const SubmissionsList = ({
               most liked submissions -
               {' '}
             </span>
-            <a data-test-id="view-all-projects-link" href={allSubmissionsPath}> View full list of solutions</a>
+            <a
+              className="text-gold"
```
Comment (ChargrilledChook) [inline app/javascript/components/project-submissions/components/submissions-list.jsx:71]: I'm assuming this is one of the apply directives we want to keep - let me know if we want to make it a Tailwind class

**Review by KevinMulhern — APPROVED** [review]
